### ISSUE TITLE
Suggestion: Move START BUY/SELL AFTER TIMESTAMP to TOKENS.json

### ISSUE THREAD

**Issue by ghost** [tsarbuig/LimitSwap#94]
**START_BUY_AFTER_TIMESTAMP**
**START_SELL_AFTER_TIMESTAMP**

are both located in the **SETTINGS.json**

My suggestion is to move both settings to the same **"Counter ANTI-BOT"** section of the **TOKENS.json**

**Comment by tsarbuig** [comment]
You are right, it should be there... but I put it in settings because it's a global parameter : it blocks the WHOLE bot before timestamp is reached

It was too hard to make it block ONE token at a time (and let the other tokens work) if user is sniping several tokens at the same time...

--> it's a good idea, but too much work, sadly, sorry

**Comment by ghost** [comment]
I see, that makes sense now :)
